version: "3.3"

services:
  node:
    build:
      context: .
      args:
        CONTAINER_VERSION: ${CONTAINER_VERSION}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        TYPE: ${TYPE}
      dockerfile: Dockerfile
    volumes:
      - "./:/app"

  shop:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      dockerfile: DockerfileShop
    ports:
      - 8081:8081
    volumes:
      - "./:/app"
